services:
  ncat:
    image: stephengpope/no-code-architects-toolkit:latest
    ports:
      - "8080:8080"  # Use different port since Plesk has 80/443
    command: gunicorn app:app -b 0.0.0.0:8080
    volumes:
      - storage:/var/www/html/storage/app
      - logs:/var/www/html/storage/logs
    restart: unless-stopped
    shm_size: "1g"
    environment:
     - API_KEY=${API_KEY}
     - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
     - S3_ACCESS_KEY=${S3_ACCESS_KEY}
     - S3_SECRET_KEY=${S3_SECRET_KEY}
     - S3_BUCKET_NAME=${S3_BUCKET_NAME}
     - S3_REGION=${S3_REGION}
     - MAX_QUEUE_LENGTH=${MAX_QUEUE_LENGTH}
     - GUNICORN_WORKERS=${GUNICORN_WORKERS}
     - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT}
     - APP_NAME=${APP_NAME}
     - APP_DEBUG=${APP_DEBUG}
     - APP_DOMAIN=${APP_DOMAIN}
     - APP_URL=${APP_URL}
     - WHISPER_MODEL=${WHISPER_MODEL}

volumes:
  storage:
    driver: local
  logs:
    driver: local
